-- Создание баз данных для сервисов
CREATE DATABASE users_db;
CREATE DATABASE orders_db;
CREATE DATABASE notification_db;

-- Подключение к базе users_db (или создание её при необходимости)
\c users_db;

-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role::text = ANY (ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying]::text[]))
    );

-- Первичное наполнение тестовыми пользователями
INSERT INTO public.users (email, name, role)
VALUES
    ('testuser@test.com', 'Иванов Иван', 'ROLE_USER'),
    ('admin@test.com', 'Администратор', 'ROLE_ADMIN')
    ON CONFLICT (email) DO NOTHING;

