server.port=8081
# postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=qweryt123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 1. ???????? ??????????? ????????? ??????
server.error.include-message=always

# 2. ???????? ???????? ???????/??????????
server.error.include-binding-errors=always