spring.application.name=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8081
# postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=qweryt123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

server.error.include-binding-errors=always