server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      micrometer:
        enabled: true
  # orders_db
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: postgres
  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# (User Service)
user:
  service:
    url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoint:
    health:
      show-details: always
  health:
    # Если падает из-за DB/RabbitMQ в режиме отладки:
    db:
      enabled: false
  tracing:
    sampling:
      probability: 1.0 # Логируем 100% запросов
    propagation:
      type: "B3_MULTI,W3C"  # Явно включаем стандарт W3C (traceparent)
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces # Стандартный OTLP порт Jaeger
    metrics:
      export:
        enabled: false


logging:
  level:
    org:
      hibernate: ERROR
      hibernate.SQL: OFF
      springframework:
        web: DEBUG
        security: DEBUG
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{traceId:-},%X{spanId:-}] --- [%15.15t] %-40.40logger{36} : %m%n"

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3               # Начинаем вычислять % ошибок после 3 вызовов
        failureRateThreshold: 50              # Если >= 50% ошибок -> переводим в OPEN
        waitDurationInOpenState: 10000ms      # Находимся в OPEN 10 секунд
        permittedNumberOfCallsInHalfOpenState: 2
        recordExceptions:
          - org.springframework.web.server.ResponseStatusException # ◄ Добавьте класс исключения, которое кидает ваш CustomFeignErrorDecoder
          - feign.FeignException
    instances:
      user-service:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50              # Отключаем при 50% ошибок
        waitDurationInOpenState: 10000ms
        recordExceptions:
          - com.quickbite.orderservice.exception.UserServiceException