server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  # orders_db
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: qweryt123
  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# (User Service)
user:
  service:
    url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoint:
    health:
      show-details: always
  health:
    # Если падает из-за DB/RabbitMQ в режиме отладки:
    db:
      enabled: false

logging:
  level:
    org:
      hibernate: ERROR
      hibernate.SQL: OFF
      springframework:
        web: DEBUG
        security: DEBUG

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6                  # Анализируем окно из 6 последних запросов
        minimumNumberOfCalls: 4               # Минимальное кол-во запросов для расчета % ошибок
        failureRateThreshold: 50              # Если >= 50% ответили ошибкой -> переходим в OPEN
        waitDurationInOpenState: 10000ms      # Ждем 10 секунд в состоянии OPEN перед HALF-OPEN
        permittedNumberOfCallsInHalfOpenState: 2 # Кол-во тестовых запросов в состоянии HALF-OPEN
        slowCallRateThreshold: 50             # Если >= 50% запросов медленные -> OPEN
        slowCallDurationThreshold: 2000ms     # Запрос считается медленным, если идет > 2 секунд